name: knittda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_dash: ^1.0.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  kakao_flutter_sdk_user: ^1.9.7+3
  provider: ^6.1.5
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.1.2
  sentry_flutter: ^8.14.2
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/ # Pretendard 폰트 경로 추가
    - assets/image/ #image 경로 추가
    - assets/image/stage/ #image 경로 추가

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Black.otf
          weight: 900

