name: flutter_aplication_1
description: A Flutter project to showcase Pretendard font and additional dependencies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0  # 최신 버전을 사용하세요.

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.0.0 # HTTP 의존성 추가

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1 # 최신 린트 버전으로 업데이트

flutter:
  uses-material-design: true

  assets:
    - assets/font/ # Pretendard 폰트 경로 추가

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Black.otf
          weight: 900
