platform:ios,'13.0'

require '/Users/jisoolee/flutter/packages/flutter_tools/bin/podhelper.rb'

flutter_ios_podfile_setup

target 'Runner' do
    use_frameworks!
    use_modular_headers!


    flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

    target 'RunnerTests' do
        inherit!:search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
    end
end