require "base64"
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload beta app bundle to Google Play internal testing"
  lane :beta do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/betaRelease/app-beta-release.aab",
      json_key_data: Base64.decode64(ENV['PLAY_STORE_SERVICE_ACCOUNT_JSON_BASE64']),
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
